name: GitHub Actions Demo
on: [push]
jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      neo4j:
        # Docker Hub image
        image: neo4j:4.4-enterprise
        ports:
          - "7687:7687"
          - "7474:7474"
        env:
          NEO4J_AUTH: neo4j/test
          NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
          NEO4JLABS_PLUGINS: '["apoc"]'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
      - name: Composer Install
        uses: php-actions/composer@v6

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
     
      - name: PHPUnit
        uses: php-actions/phpunit@v3

      - run: echo "🍏 This job's status is ${{ job.status }}."
